name: module/nodejs

on:
  pull_request:
    paths:
      - nodejs/**
  push:
    branches:
      - "main"
    paths:
      - nodejs/**

jobs:
  test-bun:
    name: test-bun
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: dagger/run-tests
        uses: dagger/dagger-for-github@v6
        with:
          version: "latest"
          verb: call
          module: ./nodejs/tests
          args: test-bun
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
